make it a FOR AddOn
FriendsOfREDAXO/neues pull request #112
Opened 2024-09-09 13:44 UTC by tyrant88

2024-09-09 15:49 UTC, alxndr-w requested changes
Sponsoring-Hinweise und Nennung von Autoren sind bei anderen FOR auch kein Problem (mehr). Zweierlei Maß sollte hier nicht gelten.

2024-09-09 18:00 UTC, alxndr-w commented
Gut, dann fangen wir bei den anderen an – dieses hier kam später.

2024-09-09 22:22 UTC, alxndr-w commented
So, nun hör' jetzt mal auf mit dem Kindergarten @tyrant88 und fang beim prominentesten Werbe-Addon https://github.com/FriendsOfREDAXO/rexstan an, dann kannst du dich gerne an verschiedenen älteren Repositorys abarbeiten überall berechtigte Autorennamen rauszustreichen, einschließlich "deinem" search_it. 

Nur die Addons rauszuziehen, die meinen Namen beinhalten kannst du dir sparen und ich habe wichtigeres zu tun. Du scheinbar nicht, wie man merkt.

2024-09-10 00:12 UTC, tyrant88 commented
make it a FOR AddOn

2024-09-10 00:23 UTC, closed without merging

2024-09-10 11:17 UTC, alxndr-w commented
Du bist hier nicht Lead und deine eingereichten PRs enthalten mehr Änderungen als für dein berechtigtes Anliegen.

2024-09-10 15:18 UTC, tyrant88 commented
Nichts anderes ist beabsichtigt, Thorben.